"""Add latitude and longitude fields to HelpRequest.

Revision ID: 0746038abe3e
Revises: 5f9184a66bc7
Create Date: 2020-04-04 20:59:08.861264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0746038abe3e'
down_revision = '5f9184a66bc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'help_requests_helprequest',
        sa.Column('latitude', sa.Float(), nullable=True),
        )
    op.add_column(
        'help_requests_helprequest',
        sa.Column('longitude', sa.Float(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('help_requests_helprequest', 'longitude')
    op.drop_column('help_requests_helprequest', 'latitude')
    # ### end Alembic commands ###
