"""Add foreign key from HelpRequest to User

Revision ID: 4529a58bc502
Revises: f7e7f84b01ce
Create Date: 2020-04-04 12:20:28.517562

"""
import sqlalchemy as sa

from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4529a58bc502'
down_revision = 'f7e7f84b01ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'help_requests_helprequest',
        sa.Column(
            'accepted_by_id',
            postgresql.UUID(as_uuid=True),
            nullable=True,
        ),
    )
    op.create_foreign_key(
        'helprequest_id__user_id_fk',
        'help_requests_helprequest',
        'users_user',
        ['accepted_by_id'],
        ['id'],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'helprequest_id__user_id_fk',
        'help_requests_helprequest',
        type_='foreignkey',
    )
    op.drop_column('help_requests_helprequest', 'accepted_by_id')
    # ### end Alembic commands ###
