"""Adjust help_request HelpRequest fields

Revision ID: 54bc13321f2c
Revises: 4529a58bc502
Create Date: 2020-04-04 18:04:15.584973

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '54bc13321f2c'
down_revision = '4529a58bc502'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'help_requests_helprequest',
        sa.Column('call_time', sa.String(length=255), nullable=False),
    )
    op.add_column(
        'help_requests_helprequest',
        sa.Column('full_name', sa.String(length=255), nullable=False),
    )
    op.add_column(
        'help_requests_helprequest',
        sa.Column('pickup_time', sa.String(length=255), nullable=False),
    )
    op.add_column(
        'help_requests_helprequest',
        sa.Column('products', sa.Text(), nullable=False),
    )
    op.drop_column('help_requests_helprequest', 'first_name')
    op.drop_column('help_requests_helprequest', 'last_name')
    op.drop_column('help_requests_helprequest', 'things')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'help_requests_helprequest',
        sa.Column(
            'things',
            sa.VARCHAR(length=1020),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        'help_requests_helprequest',
        sa.Column(
            'last_name',
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        'help_requests_helprequest',
        sa.Column(
            'first_name',
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column('help_requests_helprequest', 'products')
    op.drop_column('help_requests_helprequest', 'pickup_time')
    op.drop_column('help_requests_helprequest', 'full_name')
    op.drop_column('help_requests_helprequest', 'call_time')
    # ### end Alembic commands ###
