"""Cast phone_number to String.

Revision ID: 5f9184a66bc7
Revises: 54bc13321f2c
Create Date: 2020-04-04 19:45:09.775295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f9184a66bc7'
down_revision = '54bc13321f2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'help_requests_helprequest',
        'phone_number',
        existing_type=sa.VARCHAR(length=255),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'help_requests_helprequest',
        'phone_number',
        existing_type=sa.VARCHAR(length=20),
        nullable=True,
    )
    # ### end Alembic commands ###
