"""Add recording_url field to HelpRequest.

Revision ID: 953bd4188164
Revises: 0746038abe3e
Create Date: 2020-04-05 06:05:37.647195

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '953bd4188164'
down_revision = '0746038abe3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'help_requests_helprequest',
        sa.Column('recording_url', sa.String(length=255), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('help_requests_helprequest', 'recording_url')
    # ### end Alembic commands ###
