"""Add help_requests HelpRequest model.

Revision ID: f7e7f84b01ce
Revises: b2974f676072
Create Date: 2020-04-04 12:05:35.998647

"""
import sqlalchemy as sa
import sqlalchemy_utils

from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f7e7f84b01ce'
down_revision = 'b2974f676072'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'help_requests_helprequest',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('first_name', sa.String(length=255), nullable=False),
        sa.Column('last_name', sa.String(length=255), nullable=False),
        sa.Column(
            'phone_number',
            sqlalchemy_utils.types.phone_number.PhoneNumberType(
                region='PL',
                length=255,
            ),
            nullable=True,
        ),
        sa.Column('address', sa.String(length=255), nullable=False),
        sa.Column('things', sa.Text(), nullable=False),
        sa.Column('finished_at', sa.DateTime(), nullable=True),
        sa.Column('accepted_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('help_requests_helprequest')
    # ### end Alembic commands ###
